[project]
name = "lblod-mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.52.2",
    "mcp>=1.9.3",
    "python-dotenv>=1.1.0",
    "sparqlwrapper>=2.0.0",
]
